name: CI Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
# job is used for creating the workflow
jobs:
  # build is used for creating enviroments and  organize the steps
  build:
    # specify the os for the job runner
    runs-on: ubuntu-latest

    steps: # a sequence of action to be performed 
    - name: Checkout code # name is user for clearify the name of the stpe in ui
      uses: actions/checkout@v3 #clone the repository to the on to the runner
    
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: install dependencies
      run: npm install

    - name: Run tests
      run: npm test
