name: CI Pipeline

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  # build is used for creating enviroments and  organize the steps
  build:
    runs-on: self-hosted
    # specify the os for the job runner
    

    steps: # a sequence of action to be performed 
    - name: Checkout code # name is user for clearify the name of the stpe in ui
      uses: actions/checkout@v3 #clone the repository to the on to the runner
    
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name : login to docker
      uses : docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t cicd_test .

    - name: Tag Docker image
      run: docker tag cicd_test:latest hishammpsn/cicd_test:latest

    - name: Push Docker image to Docker Hub
      run: docker push hishammpsn/cicd_test:latest
